on: [push, pull_request]

name: check

jobs:
  check:
    runs-on: ${{ matrix.os }}
    env:
      NOAWT: 1

    name: ${{ matrix.os }}, R ${{ matrix.r }}, Java ${{ matrix.java }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2022', 'macOS-13', 'macOS-14', 'ubuntu-22.04' ]
        r:  [ 'release' ]
        java: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install R
        uses: s-u/R-actions/install@v2
        with:
          r-version: ${{ matrix.r }}
          tools: base

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Setup R Java support
        if: runner.os != 'Windows'
        run: |
          echo export PATH=$PATH > reconf.sh
          echo export JAVA_HOME=$JAVA_HOME >> reconf.sh
          echo R CMD javareconf >> reconf.sh
          sudo bash reconf.sh
        shell: bash

      - uses: s-u/R-actions/pkg-check@v2
        with:
          build-script: sh mkdist
